### ISSUE TITLE
Improved Shop Wizard

### ISSUE THREAD

**Issue by jacobkossman** [w35l3y/userscripts#38]
I'm sure you aren't going to fix since you're working on the new version but the Shop Wizard doesn't report if you try and buy something and your inventory is over 50 items (since you can't buy anything at that point). It reports item as bought (doesn't actually buy it since it can't) and changes the quantity to 0. I'm going to take a closer look and see if i can fix it.

**Comment by w35l3y** [comment]
Yeah... the problem is the page doesn't differ successful buys or not.
It is really difficult to make sure whether the buy was ok or not.

The only thing I can think of is to add a parameter to check the inventory before and after buying items, but I think it is very time/resource consuming, specially when using it in quests.

**Comment by jacobkossman** [comment]
You should be able to check the buy page response for an error page (not
enough money, or such). I think the only other error that you can get
that's not in a red "error" message thing is the "over 50 items error" so
you can check for the specific text + image and send that in the response
as an error, and if error.length > 1 then return an error etc.
