### ISSUE TITLE
Battledome : Fight! not working

### ISSUE THREAD

**Issue by friendly-trenchcoat** [w35l3y/userscripts#41]
I tried both chrome and firefox, and it did nothing in either.

In chrome, there's a massive wall of errors, almost all of which are about a missing semicolon.

In firefox, there are no errors, but it still doesn't work.

**Comment by mediterra2** [comment]
This hasn't worked for probably 6 months or more

**Comment by w35l3y** [comment]
None of them were designed to work in Chrome.

More details about the error is necessary.
Please, consider reading the guide for contributing.

**Comment by mediterra2** [comment]
It hasn't worked in Firefox in several months either.  It comes up with "fight" at the bottom but goes nowhere.  I've tried it on several different computers at 3 different locations.

**Comment by w35l3y** [comment]
There is a template that should be followed whenever an issue is found.
It is found in the [Guidelines for Contributing](/w35l3y/userscripts/blob/master/CONTRIBUTING.md).

**Comment by Sassenach** [comment]
**Browser:** VERSION<br /> Firefox 45.0.1
**Greasemonkey:** VERSION<br /> Greasemonkey 3.5
**Script:** NAME VERSION<br /> Neopets : Battledome : Fight! 2.2.0, Neopets : Dice-A-Roo 6.6.0.  There could be a couple of other scripts that have stopped working but these are the ones that I like the most.
**Accessed url:** URL<br />
**Installation url:** URL<br />
**Error Message:** MESSAGE<br />
**Obs.:** OBSERVATION<br /> 
MACbook running OSX 10.9.4.  I have been using a lot of your scipts for years, trust then, rely on them and I truly appreciate you sharing them.  I recently upgraded to the most recent version of Greasemonkey and Firefox and some of your scripts have stopped working for me.  I really miss the Battledome and Dice-A-Roo script.  Since the scripts stopped working for me I have downgraded to an older version of firefox, various versions of greasemonkey, totally reset firefox and reinstalled all of my extensions and scripts one-by-one without success.<br/>
Battledome : Fight! 2.2.0 - refreshes the page - approximately the time it would take the script to run through a battle but no battle takes place.<br/>
Dice-A-Roo 6.6.0 just sits there doing nothing.

**Comment by w35l3y** [comment]
There isn't a reasonable reason to have an unmodified script be broken unexpectedly.
So, something was updated (GM or Firefox) that broke the scripts.
In this case, it was Greasemonkey.

Sometimes, Greasemonkey updates and breaks a lot of scripts.
My recommendation is to disable auto-update of this extension.
