### ISSUE TITLE
Moltara worms

### ISSUE THREAD

**Issue by ghost** [w35l3y/userscripts#54]
Hi w35l3y,

I am a huge fan of your scripts. I was wondering if the (old) script of "Moltara worms and gears" is going to be updated some time, and if you could recommend me some books or web pages to learn javascript, so I could help. I am a Mexican mathematician, and I am reading the stuff of this page https://javascript.info/

By the way, the "Faerie Crossword" and "Mysterious Negg Solver" are not working, I do not know if you had already noticed this.

Greetings!

**Comment by w35l3y** [comment]
Most of my scripts that are on the [backup](https://github.com/w35l3y/userscripts/tree/master/backup) folder should work (except the ones on the "wontfix" folder)

[Moltara Gears + Worms](https://github.com/w35l3y/userscripts/raw/master/backup/64141.user.js) (backup)
[Faerie Crossword](https://github.com/w35l3y/userscripts/raw/master/scripts/Neopets_Faerie_Crossword/76450.user.js)
[Mysterious Negg Solver](https://github.com/w35l3y/userscripts/raw/master/scripts/Neopets_Mysterious_Negg_Solver/131454.user.js)

Just tested all of them.
The first 2 scripts are working on both browsers (GM+Firefox and TM+Chrome).
"Mysterious Negg Solver" is working only on Chrome due to incompatibility of jQuery with GM sandbox.
If this is not the case for any of them, then please consider creating a new issue with more technical details about the problem.

Nowadays I only use [JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript), but it is good only if you really know what you are looking for.
If you don't know where to start, then your link seems to be a good page.
